app = "uniconnect-dashboard-web"
primary_region = "gru"

[build]
  dockerfile = "web/Dockerfile"

[build.args]
  VITE_API_URL = "https://uniconnect-backend-grupo-2.fly.dev/api/v1"
  VITE_WS_URL = "wss://uniconnect-backend-grupo-2.fly.dev"
  VITE_SUPABASE_URL = "https://becitrklvpadvjwdbmck.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_FkHanjxqCZ7LDaQa1AomSg_xThwhZxW"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"
